version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.1
    - 12.7.2
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.16
    - 13.0.6
    - 13.1.1
    - 13.1.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-tooltip
    versions:
    - 4.2.13
    - 4.2.14
    - 4.2.15
    - 4.2.17
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: algoliasearch
    versions:
    - 4.8.4
    - 4.8.5
    - 4.8.6
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.2
